### ISSUE TITLE
Failed to initiate profile lookup. Please try again.

### ISSUE THREAD

**Issue by darkhacknet** [efiml/PersonaAI#1]
Nice script bro, 

I having this issue while trying to find some fb ID. Im using the same ID than you. 

[20/Aug/2024 18:25:33] "POST /analyze HTTP/1.1" 500 -
Received Facebook ID: bohdana.luzan
Triggering psycho profile lookup...
Failed to initiate profile lookup.

Of course I have a plan on IRBIS ! 

Hope that you can help to solve this, thanks in advance.

**Comment by efiml** [comment]
Hi there,

Thank you for your feedback! It seems like you're encountering an issue while trying to analyze a Facebook ID.

Could you please double-check that there are no spaces added before or after the Facebook ID "bohdana.luzan" when you input it? Sometimes, leading or trailing spaces can cause the request to fail.

Also, please ensure that your Lookup ID for the Psychological Portrait is set to 180 on the IRBIS Developer page. This is crucial for the correct operation of the PersonaAI tool.

If the issue persists, please let me know, and we can further investigate.

Thanks!
