### ISSUE TITLE
Error Validating API key

### ISSUE THREAD

**Issue by darkhacknet** [efiml/PersonaAI#2]
My api key is not validated correctly trough command line 

python personaai.py -k $2bxxxxxxxxxxxxxxxxx/TMZ 
    ____                                   ___    ____
   / __ \___  ______________  ____  ____ _/   |  /  _/                       
  / /_/ / _ \/ ___/ ___/ __ \/ __ \/ __ `/ /| |  / /                         
 / ____/  __/ /  (__  ) /_/ / / / / /_/ / ___ |_/ /                          
/_/    \___/_/  /____/\____/_/ /_/\__,_/_/  |_/___/                          
                                                                             
                                                                             
Welcome to PersonaAI, your tool for generating AI-based psychological profiles.
To get started, please enter your IRBIS API key.
Validating API key: $b/TMZ
Error validating API key: 404 {"statusCode":404,"message":"User not found"}
Invalid API key. Please try again.

My api key is valid and the web app is validating correctly. 

Thanks !

**Comment by efiml** [comment]
Hi there,

Thank you for bringing this to my attention! It seems like the issue may be related to how the API key is being passed in the command line.

When using the CLI, please make sure to enclose your API key in single quotes to prevent any special characters from causing issues. For example:

bash
Copy code
python personaai.py -k '$2bxxxxxxxxxxxxxxxxx/TMZ'
This should resolve the issue you're experiencing. If the problem persists, please let me know.

Thanks!

**Comment by darkhacknet** [comment]
Thanks a lot my friend, I will do it. Close this if you want.
